version: '3'

services:

  database:
    container_name: database
    ports:
    - "3306:3306"
    image: mysql/mysql-server:8.0
    volumes:
    - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    networks:
      - sm_network

  sm:
    container_name: sm
    depends_on:
    - database
    image: socialmedia:2.2
    ports:
    - "8080:8080"
    restart: always
    environment:
      DB_HOST:
      DB_PORT: 3306
      DB_USER:
      DB_PASS:
      DB_NAME:
      API_PORT: 8080
      SECRET_KEY: ''
    networks:
      - sm_network

networks:
  sm_network:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/.docker-volumes/mysql/socialmedia
